disabled_rules:
  - line_length
  - trailing_whitespace
  - todo
  - identifier_name
  - type_name

excluded:
  - Pods
  - Carthage
  - DerivedData
  - build
  - Tests
  - docs

opt_in_rules:
  - empty_count
  - empty_string

line_length: 200
file_length:
  warning: 1000
  error: 2000
